#!/bin/bash

tools=$(dirname $(dirname $(readlink -f $BASH_SOURCE)))

_afrender() {
    echo $tools
    pkill -fc -9 bin.afrender
    if [ "$HOME" == "" ] ; then
        mkdir -p /tmp/afrender/.cgru
        HOME=/tmp/afrender
        echo '{"cgru_config":{ "af_servername":"farm.local" }}' > $HOME/.cgru/config.json
    fi
    export HOME
    source $tools/init/bash
    # alias
    $tools/scripts/run afrender -hostname $(hostname) -V
}

_afrender 2>&1 | tee  /var/log/afrender.log
