#!/bin/sh



cat /sys/devices/system/cpu/cpu?/cpufreq/scaling_max_freq

if [ "$1" != "" ] ; then

	echo $1  | sudo tee /sys/devices/system/cpu/cpu?/cpufreq/scaling_max_freq
	cat /sys/devices/system/cpu/cpu?/cpufreq/scaling_max_freq
fi
