#!/usr/bin/env python


import sys,os
import pipe.farm as farm


cpus = 9999
if len(sys.argv)<5:
    print '''
================================================================================
ERROR: Syntax error... use:

    hsubmit [houdini scene file] [ini frame] [end frame] [output_driver] <cpus>
    
    
the <cpu> parameter is optional. If not specified, it will use as many cpus as
it can!
    
================================================================================
'''

else:
    if len(sys.argv)>5:
        cpus = int(sys.argv[5])

    jobid = farm.houdini(
        scene       = os.path.abspath(sys.argv[1]), 
        driver      = sys.argv[4], 
        renderer    = 'mantra', 
        name        = 'HSUBMIT',
        CPUS        = cpus, 
        priority    = 9999, 
        range       = range(int(sys.argv[2]), int(sys.argv[3])+1, 1), 
        group       = 'pipe'
    ).submit()
    print 'job id: %s' % str(jobid)
