#!/bin/bash 



export PATH=$PATH:`pwd`:/atomo/pipeline/libs/linux/x86_64/gcc-4.1.2/osl/1.4.1/bin/
export LD_LIBRARY_PATH=/atomo/pipeline/libs/linux/x86_64/gcc-4.1.2/osl/1.4.1/lib/:/atomo/pipeline/libs/linux/x86_64/gcc-4.1.2/python/2.6.8/lib/

/atomo/pipeline/libs/linux/x86_64/gcc-4.1.2/osl/1.4.1/bin/oslc "$@"
