#!/usr/bin/python2

import sys,os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(sys.argv[0])))+'/python/' )
import pipe
os.environ['STUDIO']=os.path.dirname(pipe.roots().jobs().strip('/'))

if 'dbusService' not in sys.argv[1]:
    pipe.libs.version.set( python = '3.9' )

pipe.libs.python().run('python')
