#!/usr/bin/python 

import sys, pipe


if '-l' in sys.argv:
    classList = pipe.libsDB().keys()
    baseClass = pipe.apps.baseLib
    title = 'Library Versions:'

else:
    classList = pipe.apps.appsDB().keys()
    baseClass = pipe.apps.baseApp
    title = 'Application Versions:'

classList.sort()
print "_"*120
print "% 20s" %title
print "-"*20+'+'
for each in classList:
    print "% 19s |" % each,
    print baseClass(each).version()
print "-"*20+'+'
#print "-"*120
print

