import pipe, os


src = [
    'AtomoAOV.cpp',
    # 'AtomoOcc.cpp',
#    'AtomoOcclusion.cpp',
]

def versionSort(versions):
    def method(v):
        v = filter(lambda x: x.isdigit() or x in '.', v.split('b')[0])
        return str(float(v.split('.')[0])*10000+float(v.split('.')[:2][-1])) + v.split('b')[-1]
    tmp =  sorted( versions, key=method, reverse=True )
    tmp = [ x for x in tmp if float('.'.join(x.split('.')[0:2])) > 20.0 ]
    print tmp
    return tmp

prman = pipe.apps.prman()

# only build for renderman 20 and up
for pv in versionSort(prman.versionList()):
    env = Environment()
    pipe.apps.version.set(prman = pv)

    env['SHLIBPREFIX']  = ''
    env['CC']           = pipe.libs.python().path('../../gcc/4.8.3/bin/g++')
    env['CXX']           = pipe.libs.python().path('../../gcc/4.8.3/bin/g++')
    env['LD']           = '$(CC) -shared'
    env['CCFLAGS']      = '-Wno-deprecated -std=c++11 -fPIC -I%s' % pipe.apps.prman().path('RenderManProServer-%s/include' % pv)
    env['CCFLAGS']     += ' -I%s' % pipe.apps.prman().path('RenderManProServer-%s/lib/examples/RIS/plugins/bxdf/' % pv)

    for s in src:
        build = env.Command( 'build/%s/%s' % (pv,s), s, [
            Delete("build/%s/" % pv),
            Mkdir("build/%s/" % pv),
            Copy("build/%s/" % pv, "$SOURCE"),
        ])
        shared = env.SharedLibrary( 'build/%s/%s' % (pv, os.path.splitext(s)[0]), build )
        env.Alias('install', env.Install( '%s/prman/ris/%s/pattern/' % (pipe.roots().tools(), pv), shared ))
        env.Alias('install', env.Install( '%s/prman/ris/%s/pattern/' % (pipe.roots().tools(), pv), s.replace('cpp','args') ))
