CONTAINER AINODE_ALFLAKE
{
	NAME ainode_alFlake;

	INCLUDE GVbase;

	GROUP C4DAI_ALFLAKE_MAIN_GRP
	{
		DEFAULT 1;

		AIPARAM C4DAIP_ALFLAKE_SPACE {}
		AIPARAM C4DAIP_ALFLAKE_AMOUNT {}
		AIPARAM C4DAIP_ALFLAKE_SIZE {}
		AIPARAM C4DAIP_ALFLAKE_DIVERGENCE {}
		AIPARAM C4DAIP_ALFLAKE_P {}
	}
}

