CONTAINER AINODE_ALSURFACE
{
	NAME ainode_alSurface;

	INCLUDE GVbase;

	GROUP C4DAI_ALSURFACE_MAIN_GRP
	{
		DEFAULT 1;

		GROUP C4DAI_ALSURFACE_DIFFUSE_GRP
		{
			DEFAULT 1;

			AIPARAM C4DAIP_ALSURFACE_DIFFUSESTRENGTH {}
			AIPARAM C4DAIP_ALSURFACE_DIFFUSECOLOR {}
			AIPARAM C4DAIP_ALSURFACE_DIFFUSEROUGHNESS {}
			GROUP C4DAI_ALSURFACE_BACKLIGHT_GRP
			{
				AIPARAM C4DAIP_ALSURFACE_BACKLIGHTSTRENGTH {}
				AIPARAM C4DAIP_ALSURFACE_BACKLIGHTCOLOR {}
				AIPARAM C4DAIP_ALSURFACE_BACKLIGHTINDIRECTSTRENGTH {}
			}

			GROUP C4DAI_ALSURFACE_SSS_GRP
			{
				AIPARAM C4DAIP_ALSURFACE_SSSMIX {}
				AIPARAM C4DAIP_ALSURFACE_SSSMODE {}
				AIPARAM C4DAIP_ALSURFACE_SSSDENSITYSCALE {}
				AIPARAM C4DAIP_ALSURFACE_SSSRADIUS {}
				AIPARAM C4DAIP_ALSURFACE_SSSWEIGHT1 {}
				AIPARAM C4DAIP_ALSURFACE_SSSRADIUSCOLOR {}
				AIPARAM C4DAIP_ALSURFACE_SSSRADIUS2 {}
				AIPARAM C4DAIP_ALSURFACE_SSSWEIGHT2 {}
				AIPARAM C4DAIP_ALSURFACE_SSSRADIUSCOLOR2 {}
				AIPARAM C4DAIP_ALSURFACE_SSSRADIUS3 {}
				AIPARAM C4DAIP_ALSURFACE_SSSWEIGHT3 {}
				AIPARAM C4DAIP_ALSURFACE_SSSRADIUSCOLOR3 {}
				AIPARAM C4DAIP_ALSURFACE_SSSTRACESET {}
			}

			GROUP C4DAI_ALSURFACE_ADVANCED_1_GRP
			{
				AIPARAM C4DAIP_ALSURFACE_DIFFUSEEXTRASAMPLES {}
				AIPARAM C4DAIP_ALSURFACE_SSSEXTRASAMPLES {}
				AIPARAM C4DAIP_ALSURFACE_DIFFUSEINDIRECTSTRENGTH {}
				AIPARAM C4DAIP_ALSURFACE_DIFFUSEINDIRECTCLAMP {}
				AIPARAM C4DAIP_ALSURFACE_DIFFUSENORMAL {}
				AIPARAM C4DAIP_ALSURFACE_TRACESETDIFFUSE {}
				AIPARAM C4DAIP_ALSURFACE_TRACESETBACKLIGHT {}
			}

		}

		GROUP C4DAI_ALSURFACE_SPECULAR_1_GRP
		{
			DEFAULT 1;

			AIPARAM C4DAIP_ALSURFACE_SPECULAR1STRENGTH {}
			AIPARAM C4DAIP_ALSURFACE_SPECULAR1COLOR {}
			AIPARAM C4DAIP_ALSURFACE_SPECULAR1ROUGHNESS {}
			AIPARAM C4DAIP_ALSURFACE_SPECULAR1ANISOTROPY {}
			AIPARAM C4DAIP_ALSURFACE_SPECULAR1ROTATION {}
			GROUP C4DAI_ALSURFACE_FRESNEL_GRP
			{
				DEFAULT 1;

				AIPARAM C4DAIP_ALSURFACE_SPECULAR1FRESNELMODE {}
				AIPARAM C4DAIP_ALSURFACE_SPECULAR1IOR {}
				AIPARAM C4DAIP_ALSURFACE_SPECULAR1REFLECTIVITY {}
				AIPARAM C4DAIP_ALSURFACE_SPECULAR1EDGETINT {}
			}

			GROUP C4DAI_ALSURFACE_ADVANCED_2_GRP
			{
				AIPARAM C4DAIP_ALSURFACE_SPECULAR1ROUGHNESSDEPTHSCALE {}
				AIPARAM C4DAIP_ALSURFACE_SPECULAR1EXTRASAMPLES {}
				AIPARAM C4DAIP_ALSURFACE_SPECULAR1NORMAL {}
				AIPARAM C4DAIP_ALSURFACE_SPECULAR1INDIRECTSTRENGTH {}
				AIPARAM C4DAIP_ALSURFACE_SPECULAR1INDIRECTCLAMP {}
				AIPARAM C4DAIP_ALSURFACE_TRACESETSPECULAR1 {}
				AIPARAM C4DAIP_ALSURFACE_SPECULAR1CAUSTICPATHS {}
				AIPARAM C4DAIP_ALSURFACE_SPECULAR1INTERNALDIRECT {}
				AIPARAM C4DAIP_ALSURFACE_SPECULAR1DISTRIBUTION {}
			}

		}

		GROUP C4DAI_ALSURFACE_SPECULAR_2_GRP
		{
			AIPARAM C4DAIP_ALSURFACE_SPECULAR2STRENGTH {}
			AIPARAM C4DAIP_ALSURFACE_SPECULAR2COLOR {}
			AIPARAM C4DAIP_ALSURFACE_SPECULAR2ROUGHNESS {}
			AIPARAM C4DAIP_ALSURFACE_SPECULAR2ANISOTROPY {}
			AIPARAM C4DAIP_ALSURFACE_SPECULAR2ROTATION {}
			GROUP C4DAI_ALSURFACE_FRESNEL_1_GRP
			{
				DEFAULT 1;

				AIPARAM C4DAIP_ALSURFACE_SPECULAR2FRESNELMODE {}
				AIPARAM C4DAIP_ALSURFACE_SPECULAR2IOR {}
				AIPARAM C4DAIP_ALSURFACE_SPECULAR2REFLECTIVITY {}
				AIPARAM C4DAIP_ALSURFACE_SPECULAR2EDGETINT {}
			}

			GROUP C4DAI_ALSURFACE_ADVANCED_3_GRP
			{
				AIPARAM C4DAIP_ALSURFACE_SPECULAR2ROUGHNESSDEPTHSCALE {}
				AIPARAM C4DAIP_ALSURFACE_SPECULAR2EXTRASAMPLES {}
				AIPARAM C4DAIP_ALSURFACE_SPECULAR2NORMAL {}
				AIPARAM C4DAIP_ALSURFACE_SPECULAR2INDIRECTSTRENGTH {}
				AIPARAM C4DAIP_ALSURFACE_SPECULAR2INDIRECTCLAMP {}
				AIPARAM C4DAIP_ALSURFACE_TRACESETSPECULAR2 {}
				AIPARAM C4DAIP_ALSURFACE_SPECULAR2CAUSTICPATHS {}
				AIPARAM C4DAIP_ALSURFACE_SPECULAR2INTERNALDIRECT {}
				AIPARAM C4DAIP_ALSURFACE_SPECULAR2DISTRIBUTION {}
			}

		}

		GROUP C4DAI_ALSURFACE_TRANSMISSION_GRP
		{
			AIPARAM C4DAIP_ALSURFACE_TRANSMISSIONSTRENGTH {}
			AIPARAM C4DAIP_ALSURFACE_TRANSMISSIONCOLOR {}
			AIPARAM C4DAIP_ALSURFACE_TRANSMISSIONLINKTOSPECULAR1 {}
			AIPARAM C4DAIP_ALSURFACE_TRANSMISSIONROUGHNESS {}
			AIPARAM C4DAIP_ALSURFACE_TRANSMISSIONIOR {}
			GROUP C4DAI_ALSURFACE_ATTENUATION_GRP
			{
				AIPARAM C4DAIP_ALSURFACE_SSATTENUATIONCOLOR {}
				AIPARAM C4DAIP_ALSURFACE_SSINSCATTERINGSTRENGTH {}
				AIPARAM C4DAIP_ALSURFACE_SSDENSITYSCALE {}
				AIPARAM C4DAIP_ALSURFACE_SSDIRECTION {}
			}

			GROUP C4DAI_ALSURFACE_ADVANCED_4_GRP
			{
				AIPARAM C4DAIP_ALSURFACE_TRANSMISSIONROUGHNESSDEPTHSCALE {}
				AIPARAM C4DAIP_ALSURFACE_TRANSMISSIONEXTRASAMPLES {}
				AIPARAM C4DAIP_ALSURFACE_TRANSMISSIONENABLECAUSTICS {}
				AIPARAM C4DAIP_ALSURFACE_RRTRANSMISSIONDEPTH {}
				AIPARAM C4DAIP_ALSURFACE_TRANSMISSIONCLAMP {}
				AIPARAM C4DAIP_ALSURFACE_SSSPECIFYCOEFFICIENTS {}
				AIPARAM C4DAIP_ALSURFACE_SSSCATTERING {}
				AIPARAM C4DAIP_ALSURFACE_SSABSORPTION {}
				AIPARAM C4DAIP_ALSURFACE_TRACESETTRANSMISSION {}
				AIPARAM C4DAIP_ALSURFACE_TRANSMISSIONDODIRECT {}
				AIPARAM C4DAIP_ALSURFACE_TRANSMISSIONNORMAL {}
				AIPARAM C4DAIP_ALSURFACE_TRANSMISSIONCAUSTICPATHS {}
			}

		}

		GROUP C4DAI_ALSURFACE_EMISSION_GRP
		{
			AIPARAM C4DAIP_ALSURFACE_EMISSIONSTRENGTH {}
			AIPARAM C4DAIP_ALSURFACE_EMISSIONCOLOR {}
		}

		AIPARAM C4DAIP_ALSURFACE_OPACITY {}
		GROUP C4DAI_ALSURFACE_IDS_GRP
		{
			AIPARAM C4DAIP_ALSURFACE_ID1 {}
			AIPARAM C4DAIP_ALSURFACE_ID2 {}
			AIPARAM C4DAIP_ALSURFACE_ID3 {}
			AIPARAM C4DAIP_ALSURFACE_ID4 {}
			AIPARAM C4DAIP_ALSURFACE_ID5 {}
			AIPARAM C4DAIP_ALSURFACE_ID6 {}
			AIPARAM C4DAIP_ALSURFACE_ID7 {}
			AIPARAM C4DAIP_ALSURFACE_ID8 {}
		}

		GROUP C4DAI_ALSURFACE_AOVS_GRP
		{
			AIPARAM C4DAIP_ALSURFACE_CRYPTO_ASSET_OVERRIDE {}
			AIPARAM C4DAIP_ALSURFACE_CRYPTO_OBJECT_OVERRIDE {}
			AIPARAM C4DAIP_ALSURFACE_CRYPTO_MATERIAL_OVERRIDE {}
			AIPARAM C4DAIP_ALSURFACE_STANDARDCOMPATIBLEAOVS {}
			AIPARAM C4DAIP_ALSURFACE_TRANSMITAOVS {}
			AIPARAM C4DAIP_ALSURFACE_AOV_DIFFUSE_COLOR {}
			AIPARAM C4DAIP_ALSURFACE_AOV_DIFFUSE_COLOR_CLAMP {}
			AIPARAM C4DAIP_ALSURFACE_AOV_DIRECT_DIFFUSE {}
			AIPARAM C4DAIP_ALSURFACE_AOV_DIRECT_DIFFUSE_CLAMP {}
			AIPARAM C4DAIP_ALSURFACE_AOV_DIRECT_DIFFUSE_RAW {}
			AIPARAM C4DAIP_ALSURFACE_AOV_DIRECT_DIFFUSE_RAW_CLAMP {}
			AIPARAM C4DAIP_ALSURFACE_AOV_INDIRECT_DIFFUSE {}
			AIPARAM C4DAIP_ALSURFACE_AOV_INDIRECT_DIFFUSE_CLAMP {}
			AIPARAM C4DAIP_ALSURFACE_AOV_INDIRECT_DIFFUSE_RAW {}
			AIPARAM C4DAIP_ALSURFACE_AOV_INDIRECT_DIFFUSE_RAW_CLAMP {}
			AIPARAM C4DAIP_ALSURFACE_AOV_DIRECT_BACKLIGHT {}
			AIPARAM C4DAIP_ALSURFACE_AOV_DIRECT_BACKLIGHT_CLAMP {}
			AIPARAM C4DAIP_ALSURFACE_AOV_INDIRECT_BACKLIGHT {}
			AIPARAM C4DAIP_ALSURFACE_AOV_INDIRECT_BACKLIGHT_CLAMP {}
			AIPARAM C4DAIP_ALSURFACE_AOV_DIRECT_SPECULAR {}
			AIPARAM C4DAIP_ALSURFACE_AOV_DIRECT_SPECULAR_CLAMP {}
			AIPARAM C4DAIP_ALSURFACE_AOV_INDIRECT_SPECULAR {}
			AIPARAM C4DAIP_ALSURFACE_AOV_INDIRECT_SPECULAR_CLAMP {}
			AIPARAM C4DAIP_ALSURFACE_AOV_DIRECT_SPECULAR_2 {}
			AIPARAM C4DAIP_ALSURFACE_AOV_DIRECT_SPECULAR_2_CLAMP {}
			AIPARAM C4DAIP_ALSURFACE_AOV_INDIRECT_SPECULAR_2 {}
			AIPARAM C4DAIP_ALSURFACE_AOV_INDIRECT_SPECULAR_2_CLAMP {}
			AIPARAM C4DAIP_ALSURFACE_AOV_SINGLE_SCATTER {}
			AIPARAM C4DAIP_ALSURFACE_AOV_SINGLE_SCATTER_CLAMP {}
			AIPARAM C4DAIP_ALSURFACE_AOV_SSS {}
			AIPARAM C4DAIP_ALSURFACE_AOV_SSS_CLAMP {}
			AIPARAM C4DAIP_ALSURFACE_AOV_REFRACTION {}
			AIPARAM C4DAIP_ALSURFACE_AOV_REFRACTION_CLAMP {}
			AIPARAM C4DAIP_ALSURFACE_AOV_EMISSION {}
			AIPARAM C4DAIP_ALSURFACE_AOV_EMISSION_CLAMP {}
			AIPARAM C4DAIP_ALSURFACE_AOV_UV {}
			AIPARAM C4DAIP_ALSURFACE_AOV_DEPTH {}
			AIPARAM C4DAIP_ALSURFACE_AOV_LIGHT_GROUP_1 {}
			AIPARAM C4DAIP_ALSURFACE_AOV_LIGHT_GROUP_1_CLAMP {}
			AIPARAM C4DAIP_ALSURFACE_AOV_LIGHT_GROUP_2 {}
			AIPARAM C4DAIP_ALSURFACE_AOV_LIGHT_GROUP_2_CLAMP {}
			AIPARAM C4DAIP_ALSURFACE_AOV_LIGHT_GROUP_3 {}
			AIPARAM C4DAIP_ALSURFACE_AOV_LIGHT_GROUP_3_CLAMP {}
			AIPARAM C4DAIP_ALSURFACE_AOV_LIGHT_GROUP_4 {}
			AIPARAM C4DAIP_ALSURFACE_AOV_LIGHT_GROUP_4_CLAMP {}
			AIPARAM C4DAIP_ALSURFACE_AOV_LIGHT_GROUP_5 {}
			AIPARAM C4DAIP_ALSURFACE_AOV_LIGHT_GROUP_5_CLAMP {}
			AIPARAM C4DAIP_ALSURFACE_AOV_LIGHT_GROUP_6 {}
			AIPARAM C4DAIP_ALSURFACE_AOV_LIGHT_GROUP_6_CLAMP {}
			AIPARAM C4DAIP_ALSURFACE_AOV_LIGHT_GROUP_7 {}
			AIPARAM C4DAIP_ALSURFACE_AOV_LIGHT_GROUP_7_CLAMP {}
			AIPARAM C4DAIP_ALSURFACE_AOV_LIGHT_GROUP_8 {}
			AIPARAM C4DAIP_ALSURFACE_AOV_LIGHT_GROUP_8_CLAMP {}
			AIPARAM C4DAIP_ALSURFACE_AOV_ID_1 {}
			AIPARAM C4DAIP_ALSURFACE_AOV_ID_2 {}
			AIPARAM C4DAIP_ALSURFACE_AOV_ID_3 {}
			AIPARAM C4DAIP_ALSURFACE_AOV_ID_4 {}
			AIPARAM C4DAIP_ALSURFACE_AOV_ID_5 {}
			AIPARAM C4DAIP_ALSURFACE_AOV_ID_6 {}
			AIPARAM C4DAIP_ALSURFACE_AOV_ID_7 {}
			AIPARAM C4DAIP_ALSURFACE_AOV_ID_8 {}
			AIPARAM C4DAIP_ALSURFACE_AOV_CRYPTO_ASSET {}
			AIPARAM C4DAIP_ALSURFACE_AOV_CRYPTO_OBJECT {}
			AIPARAM C4DAIP_ALSURFACE_AOV_CRYPTO_MATERIAL {}
			AIPARAM C4DAIP_ALSURFACE_AOV_SHADOW_GROUP_1 {}
			AIPARAM C4DAIP_ALSURFACE_AOV_SHADOW_GROUP_2 {}
			AIPARAM C4DAIP_ALSURFACE_AOV_SHADOW_GROUP_3 {}
			AIPARAM C4DAIP_ALSURFACE_AOV_SHADOW_GROUP_4 {}
			AIPARAM C4DAIP_ALSURFACE_AOV_SHADOW_GROUP_5 {}
			AIPARAM C4DAIP_ALSURFACE_AOV_SHADOW_GROUP_6 {}
			AIPARAM C4DAIP_ALSURFACE_AOV_SHADOW_GROUP_7 {}
			AIPARAM C4DAIP_ALSURFACE_AOV_SHADOW_GROUP_8 {}
		}

		GROUP C4DAI_ALSURFACE_ADVANCED_GRP
		{
			AIPARAM C4DAIP_ALSURFACE_RR {}
			AIPARAM C4DAIP_ALSURFACE_TRACESETALL {}
			AIPARAM C4DAIP_ALSURFACE_TRACESETSHADOWS {}
			AIPARAM C4DAIP_ALSURFACE_DEBUG {}
		}

	}
}

