CONTAINER AINODE_ALGABORNOISE
{
	NAME ainode_alGaborNoise;

	INCLUDE GVbase;

	GROUP C4DAI_ALGABORNOISE_MAIN_GRP
	{
		DEFAULT 1;

		AIPARAM C4DAIP_ALGABORNOISE_SPACE {}
		AIPARAM C4DAIP_ALGABORNOISE_FREQUENCY {}
		AIPARAM C4DAIP_ALGABORNOISE_ANISOTROPY {}
		AIPARAM C4DAIP_ALGABORNOISE_ANISOTROPYDIRECTION {}
		AIPARAM C4DAIP_ALGABORNOISE_FILTER {}
		AIPARAM C4DAIP_ALGABORNOISE_BANDWIDTH {}
		AIPARAM C4DAIP_ALGABORNOISE_IMPULSES {}
		AIPARAM C4DAIP_ALGABORNOISE_TURBULENT {}
		GROUP C4DAI_ALGABORNOISE_REMAP_GRP
		{
			AIPARAM C4DAIP_ALGABORNOISE_RMPINPUTMIN {}
			AIPARAM C4DAIP_ALGABORNOISE_RMPINPUTMAX {}
			GROUP C4DAI_ALGABORNOISE_CONTRAST_GRP
			{
				DEFAULT 1;

				AIPARAM C4DAIP_ALGABORNOISE_RMPCONTRAST {}
				AIPARAM C4DAIP_ALGABORNOISE_RMPCONTRASTPIVOT {}
			}

			GROUP C4DAI_ALGABORNOISE_BIAS_AND_GAIN_GRP
			{
				DEFAULT 1;

				AIPARAM C4DAIP_ALGABORNOISE_RMPBIAS {}
				AIPARAM C4DAIP_ALGABORNOISE_RMPGAIN {}
			}

			AIPARAM C4DAIP_ALGABORNOISE_RMPOUTPUTMIN {}
			AIPARAM C4DAIP_ALGABORNOISE_RMPOUTPUTMAX {}
			GROUP C4DAI_ALGABORNOISE_CLAMP_GRP
			{
				DEFAULT 1;

				AIPARAM C4DAIP_ALGABORNOISE_RMPCLAMPENABLE {}
				AIPARAM C4DAIP_ALGABORNOISE_RMPTHRESHOLD {}
				AIPARAM C4DAIP_ALGABORNOISE_RMPCLAMPMIN {}
				AIPARAM C4DAIP_ALGABORNOISE_RMPCLAMPMAX {}
			}

		}

		AIPARAM C4DAIP_ALGABORNOISE_COLOR1 {}
		AIPARAM C4DAIP_ALGABORNOISE_COLOR2 {}
		AIPARAM C4DAIP_ALGABORNOISE_P {}
	}
}

