CONTAINER AINODE_ALFRACTAL
{
	NAME ainode_alFractal;

	INCLUDE GVbase;

	GROUP C4DAI_ALFRACTAL_MAIN_GRP
	{
		DEFAULT 1;

		AIPARAM C4DAIP_ALFRACTAL_MODE {}
		AIPARAM C4DAIP_ALFRACTAL_SPACE {}
		AIPARAM C4DAIP_ALFRACTAL_SCALE {}
		AIPARAM C4DAIP_ALFRACTAL_FREQUENCY {}
		AIPARAM C4DAIP_ALFRACTAL_TIME {}
		AIPARAM C4DAIP_ALFRACTAL_OCTAVES {}
		AIPARAM C4DAIP_ALFRACTAL_DISTORTION {}
		AIPARAM C4DAIP_ALFRACTAL_LACUNARITY {}
		AIPARAM C4DAIP_ALFRACTAL_GAIN {}
		AIPARAM C4DAIP_ALFRACTAL_TURBULENT {}
		GROUP C4DAI_ALFRACTAL_REMAP_GRP
		{
			AIPARAM C4DAIP_ALFRACTAL_RMPINPUTMIN {}
			AIPARAM C4DAIP_ALFRACTAL_RMPINPUTMAX {}
			GROUP C4DAI_ALFRACTAL_CONTRAST_GRP
			{
				DEFAULT 1;

				AIPARAM C4DAIP_ALFRACTAL_RMPCONTRAST {}
				AIPARAM C4DAIP_ALFRACTAL_RMPCONTRASTPIVOT {}
			}

			GROUP C4DAI_ALFRACTAL_BIAS_AND_GAIN_GRP
			{
				DEFAULT 1;

				AIPARAM C4DAIP_ALFRACTAL_RMPBIAS {}
				AIPARAM C4DAIP_ALFRACTAL_RMPGAIN {}
			}

			AIPARAM C4DAIP_ALFRACTAL_RMPOUTPUTMIN {}
			AIPARAM C4DAIP_ALFRACTAL_RMPOUTPUTMAX {}
			GROUP C4DAI_ALFRACTAL_CLAMP_GRP
			{
				DEFAULT 1;

				AIPARAM C4DAIP_ALFRACTAL_RMPCLAMPENABLE {}
				AIPARAM C4DAIP_ALFRACTAL_RMPTHRESHOLD {}
				AIPARAM C4DAIP_ALFRACTAL_RMPCLAMPMIN {}
				AIPARAM C4DAIP_ALFRACTAL_RMPCLAMPMAX {}
			}

		}

		AIPARAM C4DAIP_ALFRACTAL_COLOR1 {}
		AIPARAM C4DAIP_ALFRACTAL_COLOR2 {}
		AIPARAM C4DAIP_ALFRACTAL_P {}
	}
}

