CONTAINER AINODE_ALSWITCHFLOAT
{
	NAME ainode_alSwitchFloat;

	INCLUDE GVbase;

	GROUP C4DAI_ALSWITCHFLOAT_MAIN_GRP
	{
		DEFAULT 1;

		AIPARAM C4DAIP_ALSWITCHFLOAT_INPUTA {}
		AIPARAM C4DAIP_ALSWITCHFLOAT_INPUTB {}
		AIPARAM C4DAIP_ALSWITCHFLOAT_INPUTC {}
		AIPARAM C4DAIP_ALSWITCHFLOAT_INPUTD {}
		AIPARAM C4DAIP_ALSWITCHFLOAT_INPUTE {}
		AIPARAM C4DAIP_ALSWITCHFLOAT_INPUTF {}
		AIPARAM C4DAIP_ALSWITCHFLOAT_INPUTG {}
		AIPARAM C4DAIP_ALSWITCHFLOAT_INPUTH {}
		AIPARAM C4DAIP_ALSWITCHFLOAT_MIX {}
		AIPARAM C4DAIP_ALSWITCHFLOAT_THRESHOLD {}
	}
}

