CONTAINER AINODE_ALREMAPCOLOR
{
	NAME ainode_alRemapColor;

	INCLUDE GVbase;

	GROUP C4DAI_ALREMAPCOLOR_MAIN_GRP
	{
		DEFAULT 1;

		AIPARAM C4DAIP_ALREMAPCOLOR_INPUT {}
		AIPARAM C4DAIP_ALREMAPCOLOR_GAMMA {}
		AIPARAM C4DAIP_ALREMAPCOLOR_SATURATION {}
		AIPARAM C4DAIP_ALREMAPCOLOR_HUEOFFSET {}
		GROUP C4DAI_ALREMAPCOLOR_CONTRAST_GRP
		{
			AIPARAM C4DAIP_ALREMAPCOLOR_CONTRAST {}
			AIPARAM C4DAIP_ALREMAPCOLOR_CONTRASTPIVOT {}
		}

		AIPARAM C4DAIP_ALREMAPCOLOR_GAIN {}
		AIPARAM C4DAIP_ALREMAPCOLOR_EXPOSURE {}
		AIPARAM C4DAIP_ALREMAPCOLOR_MASK {}
	}
}

