CONTAINER AINODE_ALLAYERCOLOR
{
	NAME ainode_alLayerColor;

	INCLUDE GVbase;

	GROUP C4DAI_ALLAYERCOLOR_MAIN_GRP
	{
		DEFAULT 1;

		AIPARAM C4DAIP_ALLAYERCOLOR_CLAMP_RESULT {}
		GROUP C4DAI_ALLAYERCOLOR_BACKGROUND_GRP
		{
			DEFAULT 1;

			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER1NAME {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER1ENABLED {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER1 {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER1A {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER1BLEND {}
		}

		GROUP C4DAI_ALLAYERCOLOR_LAYER_2_GRP
		{
			DEFAULT 1;

			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER2NAME {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER2ENABLED {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER2 {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER2A {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER2BLEND {}
		}

		GROUP C4DAI_ALLAYERCOLOR_LAYER_3_GRP
		{
			DEFAULT 1;

			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER3NAME {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER3ENABLED {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER3 {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER3A {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER3BLEND {}
		}

		GROUP C4DAI_ALLAYERCOLOR_LAYER_4_GRP
		{
			DEFAULT 1;

			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER4NAME {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER4ENABLED {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER4 {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER4A {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER4BLEND {}
		}

		GROUP C4DAI_ALLAYERCOLOR_LAYER_5_GRP
		{
			DEFAULT 1;

			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER5NAME {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER5ENABLED {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER5 {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER5A {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER5BLEND {}
		}

		GROUP C4DAI_ALLAYERCOLOR_LAYER_6_GRP
		{
			DEFAULT 1;

			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER6NAME {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER6ENABLED {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER6 {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER6A {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER6BLEND {}
		}

		GROUP C4DAI_ALLAYERCOLOR_LAYER_7_GRP
		{
			DEFAULT 1;

			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER7NAME {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER7ENABLED {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER7 {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER7A {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER7BLEND {}
		}

		GROUP C4DAI_ALLAYERCOLOR_LAYER_8_GRP
		{
			DEFAULT 1;

			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER8NAME {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER8ENABLED {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER8 {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER8A {}
			AIPARAM C4DAIP_ALLAYERCOLOR_LAYER8BLEND {}
		}

	}
}

