CONTAINER AINODE_ALPATTERN
{
	NAME ainode_alPattern;

	INCLUDE GVbase;

	GROUP C4DAI_ALPATTERN_MAIN_GRP
	{
		DEFAULT 1;

		AIPARAM C4DAIP_ALPATTERN_SPACE {}
		AIPARAM C4DAIP_ALPATTERN_AXIS {}
		AIPARAM C4DAIP_ALPATTERN_SHAPE {}
		AIPARAM C4DAIP_ALPATTERN_FREQUENCY {}
		AIPARAM C4DAIP_ALPATTERN_OFFSET {}
		GROUP C4DAI_ALPATTERN_REMAP_GRP
		{
			AIPARAM C4DAIP_ALPATTERN_RMPINPUTMIN {}
			AIPARAM C4DAIP_ALPATTERN_RMPINPUTMAX {}
			GROUP C4DAI_ALPATTERN_CONTRAST_GRP
			{
				DEFAULT 1;

				AIPARAM C4DAIP_ALPATTERN_RMPCONTRAST {}
				AIPARAM C4DAIP_ALPATTERN_RMPCONTRASTPIVOT {}
			}

			GROUP C4DAI_ALPATTERN_BIAS_AND_GAIN_GRP
			{
				DEFAULT 1;

				AIPARAM C4DAIP_ALPATTERN_RMPBIAS {}
				AIPARAM C4DAIP_ALPATTERN_RMPGAIN {}
			}

			AIPARAM C4DAIP_ALPATTERN_RMPOUTPUTMIN {}
			AIPARAM C4DAIP_ALPATTERN_RMPOUTPUTMAX {}
			GROUP C4DAI_ALPATTERN_CLAMP_GRP
			{
				DEFAULT 1;

				AIPARAM C4DAIP_ALPATTERN_RMPCLAMPENABLE {}
				AIPARAM C4DAIP_ALPATTERN_RMPTHRESHOLD {}
				AIPARAM C4DAIP_ALPATTERN_RMPCLAMPMIN {}
				AIPARAM C4DAIP_ALPATTERN_RMPCLAMPMAX {}
			}

		}

		AIPARAM C4DAIP_ALPATTERN_COLOR1 {}
		AIPARAM C4DAIP_ALPATTERN_COLOR2 {}
		AIPARAM C4DAIP_ALPATTERN_P {}
	}
}

