CONTAINER AINODE_ALBLACKBODY
{
	NAME ainode_alBlackbody;

	INCLUDE GVbase;

	GROUP C4DAI_ALBLACKBODY_MAIN_GRP
	{
		DEFAULT 1;

		AIPARAM C4DAIP_ALBLACKBODY_TEMPERATURE {}
		AIPARAM C4DAIP_ALBLACKBODY_STRENGTH {}
		GROUP C4DAI_ALBLACKBODY_ADVANCED_GRP
		{
			AIPARAM C4DAIP_ALBLACKBODY_PHYSICALINTENSITY {}
			AIPARAM C4DAIP_ALBLACKBODY_PHYSICALEXPOSURE {}
		}

	}
}

