CONTAINER AINODE_ALSWITCHCOLOR
{
	NAME ainode_alSwitchColor;

	INCLUDE GVbase;

	GROUP C4DAI_ALSWITCHCOLOR_MAIN_GRP
	{
		DEFAULT 1;

		AIPARAM C4DAIP_ALSWITCHCOLOR_INPUTA {}
		AIPARAM C4DAIP_ALSWITCHCOLOR_INPUTB {}
		AIPARAM C4DAIP_ALSWITCHCOLOR_INPUTC {}
		AIPARAM C4DAIP_ALSWITCHCOLOR_INPUTD {}
		AIPARAM C4DAIP_ALSWITCHCOLOR_INPUTE {}
		AIPARAM C4DAIP_ALSWITCHCOLOR_INPUTF {}
		AIPARAM C4DAIP_ALSWITCHCOLOR_INPUTG {}
		AIPARAM C4DAIP_ALSWITCHCOLOR_INPUTH {}
		AIPARAM C4DAIP_ALSWITCHCOLOR_MIX {}
		AIPARAM C4DAIP_ALSWITCHCOLOR_THRESHOLD {}
	}
}

