CONTAINER AINODE_ALLAYERFLOAT
{
	NAME ainode_alLayerFloat;

	INCLUDE GVbase;

	GROUP C4DAI_ALLAYERFLOAT_MAIN_GRP
	{
		DEFAULT 1;

		GROUP C4DAI_ALLAYERFLOAT_BACKGROUND_GRP
		{
			DEFAULT 1;

			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER1NAME {}
			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER1ENABLED {}
			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER1 {}
			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER1A {}
		}

		GROUP C4DAI_ALLAYERFLOAT_LAYER_2_GRP
		{
			DEFAULT 1;

			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER2NAME {}
			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER2ENABLED {}
			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER2 {}
			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER2A {}
		}

		GROUP C4DAI_ALLAYERFLOAT_LAYER_3_GRP
		{
			DEFAULT 1;

			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER3NAME {}
			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER3ENABLED {}
			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER3 {}
			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER3A {}
		}

		GROUP C4DAI_ALLAYERFLOAT_LAYER_4_GRP
		{
			DEFAULT 1;

			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER4NAME {}
			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER4ENABLED {}
			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER4 {}
			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER4A {}
		}

		GROUP C4DAI_ALLAYERFLOAT_LAYER_5_GRP
		{
			DEFAULT 1;

			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER5NAME {}
			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER5ENABLED {}
			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER5 {}
			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER5A {}
		}

		GROUP C4DAI_ALLAYERFLOAT_LAYER_6_GRP
		{
			DEFAULT 1;

			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER6NAME {}
			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER6ENABLED {}
			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER6 {}
			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER6A {}
		}

		GROUP C4DAI_ALLAYERFLOAT_LAYER_7_GRP
		{
			DEFAULT 1;

			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER7NAME {}
			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER7ENABLED {}
			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER7 {}
			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER7A {}
		}

		GROUP C4DAI_ALLAYERFLOAT_LAYER_8_GRP
		{
			DEFAULT 1;

			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER8NAME {}
			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER8ENABLED {}
			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER8 {}
			AIPARAM C4DAIP_ALLAYERFLOAT_LAYER8A {}
		}

	}
}

