CONTAINER AINODE_ALINPUTSCALAR
{
	NAME ainode_alInputScalar;

	INCLUDE GVbase;

	GROUP C4DAI_ALINPUTSCALAR_MAIN_GRP
	{
		DEFAULT 1;

		AIPARAM C4DAIP_ALINPUTSCALAR_INPUT {}
		AIPARAM C4DAIP_ALINPUTSCALAR_USERNAME {}
		GROUP C4DAI_ALINPUTSCALAR_REMAP_GRP
		{
			AIPARAM C4DAIP_ALINPUTSCALAR_RMPINPUTMIN {}
			AIPARAM C4DAIP_ALINPUTSCALAR_RMPINPUTMAX {}
			GROUP C4DAI_ALINPUTSCALAR_CONTRAST_GRP
			{
				DEFAULT 1;

				AIPARAM C4DAIP_ALINPUTSCALAR_RMPCONTRAST {}
				AIPARAM C4DAIP_ALINPUTSCALAR_RMPCONTRASTPIVOT {}
			}

			GROUP C4DAI_ALINPUTSCALAR_BIAS_AND_GAIN_GRP
			{
				DEFAULT 1;

				AIPARAM C4DAIP_ALINPUTSCALAR_RMPBIAS {}
				AIPARAM C4DAIP_ALINPUTSCALAR_RMPGAIN {}
			}

			AIPARAM C4DAIP_ALINPUTSCALAR_RMPOUTPUTMIN {}
			AIPARAM C4DAIP_ALINPUTSCALAR_RMPOUTPUTMAX {}
			GROUP C4DAI_ALINPUTSCALAR_CLAMP_GRP
			{
				DEFAULT 1;

				AIPARAM C4DAIP_ALINPUTSCALAR_RMPCLAMPENABLE {}
				AIPARAM C4DAIP_ALINPUTSCALAR_RMPTHRESHOLD {}
				AIPARAM C4DAIP_ALINPUTSCALAR_RMPCLAMPMIN {}
				AIPARAM C4DAIP_ALINPUTSCALAR_RMPCLAMPMAX {}
			}

		}

	}
}

