CONTAINER AINODE_ALFLOWNOISE
{
	NAME ainode_alFlowNoise;

	INCLUDE GVbase;

	GROUP C4DAI_ALFLOWNOISE_MAIN_GRP
	{
		DEFAULT 1;

		AIPARAM C4DAIP_ALFLOWNOISE_SPACE {}
		AIPARAM C4DAIP_ALFLOWNOISE_FREQUENCY {}
		AIPARAM C4DAIP_ALFLOWNOISE_OCTAVES {}
		AIPARAM C4DAIP_ALFLOWNOISE_LACUNARITY {}
		AIPARAM C4DAIP_ALFLOWNOISE_GAIN {}
		AIPARAM C4DAIP_ALFLOWNOISE_ANGLE {}
		AIPARAM C4DAIP_ALFLOWNOISE_ADVECTION {}
		AIPARAM C4DAIP_ALFLOWNOISE_TURBULENT {}
		GROUP C4DAI_ALFLOWNOISE_REMAP_GRP
		{
			AIPARAM C4DAIP_ALFLOWNOISE_RMPINPUTMIN {}
			AIPARAM C4DAIP_ALFLOWNOISE_RMPINPUTMAX {}
			GROUP C4DAI_ALFLOWNOISE_CONTRAST_GRP
			{
				DEFAULT 1;

				AIPARAM C4DAIP_ALFLOWNOISE_RMPCONTRAST {}
				AIPARAM C4DAIP_ALFLOWNOISE_RMPCONTRASTPIVOT {}
			}

			GROUP C4DAI_ALFLOWNOISE_BIAS_AND_GAIN_GRP
			{
				DEFAULT 1;

				AIPARAM C4DAIP_ALFLOWNOISE_RMPBIAS {}
				AIPARAM C4DAIP_ALFLOWNOISE_RMPGAIN {}
			}

			AIPARAM C4DAIP_ALFLOWNOISE_RMPOUTPUTMIN {}
			AIPARAM C4DAIP_ALFLOWNOISE_RMPOUTPUTMAX {}
			GROUP C4DAI_ALFLOWNOISE_CLAMP_GRP
			{
				DEFAULT 1;

				AIPARAM C4DAIP_ALFLOWNOISE_RMPCLAMPENABLE {}
				AIPARAM C4DAIP_ALFLOWNOISE_RMPTHRESHOLD {}
				AIPARAM C4DAIP_ALFLOWNOISE_RMPCLAMPMIN {}
				AIPARAM C4DAIP_ALFLOWNOISE_RMPCLAMPMAX {}
			}

		}

		AIPARAM C4DAIP_ALFLOWNOISE_COLOR1 {}
		AIPARAM C4DAIP_ALFLOWNOISE_COLOR2 {}
		AIPARAM C4DAIP_ALFLOWNOISE_P {}
	}
}

