CONTAINER AINODE_ALJITTERCOLOR
{
	NAME ainode_alJitterColor;

	INCLUDE GVbase;

	GROUP C4DAI_ALJITTERCOLOR_MAIN_GRP
	{
		DEFAULT 1;

		AIPARAM C4DAIP_ALJITTERCOLOR_INPUT {}
		AIPARAM C4DAIP_ALJITTERCOLOR_MINSATURATION {}
		AIPARAM C4DAIP_ALJITTERCOLOR_MAXSATURATION {}
		AIPARAM C4DAIP_ALJITTERCOLOR_MINGAIN {}
		AIPARAM C4DAIP_ALJITTERCOLOR_MAXGAIN {}
		AIPARAM C4DAIP_ALJITTERCOLOR_MINHUEOFFSET {}
		AIPARAM C4DAIP_ALJITTERCOLOR_MAXHUEOFFSET {}
		AIPARAM C4DAIP_ALJITTERCOLOR_CLAMP {}
		AIPARAM C4DAIP_ALJITTERCOLOR_SIGNAL {}
	}
}

