CONTAINER AINODE_ALREMAPFLOAT
{
	NAME ainode_alRemapFloat;

	INCLUDE GVbase;

	GROUP C4DAI_ALREMAPFLOAT_MAIN_GRP
	{
		DEFAULT 1;

		AIPARAM C4DAIP_ALREMAPFLOAT_INPUT {}
		GROUP C4DAI_ALREMAPFLOAT_REMAP_GRP
		{
			AIPARAM C4DAIP_ALREMAPFLOAT_RMPINPUTMIN {}
			AIPARAM C4DAIP_ALREMAPFLOAT_RMPINPUTMAX {}
			GROUP C4DAI_ALREMAPFLOAT_CONTRAST_GRP
			{
				DEFAULT 1;

				AIPARAM C4DAIP_ALREMAPFLOAT_RMPCONTRAST {}
				AIPARAM C4DAIP_ALREMAPFLOAT_RMPCONTRASTPIVOT {}
			}

			GROUP C4DAI_ALREMAPFLOAT_BIAS_AND_GAIN_GRP
			{
				DEFAULT 1;

				AIPARAM C4DAIP_ALREMAPFLOAT_RMPBIAS {}
				AIPARAM C4DAIP_ALREMAPFLOAT_RMPGAIN {}
			}

			AIPARAM C4DAIP_ALREMAPFLOAT_RMPOUTPUTMIN {}
			AIPARAM C4DAIP_ALREMAPFLOAT_RMPOUTPUTMAX {}
			GROUP C4DAI_ALREMAPFLOAT_CLAMP_GRP
			{
				DEFAULT 1;

				AIPARAM C4DAIP_ALREMAPFLOAT_RMPCLAMPENABLE {}
				AIPARAM C4DAIP_ALREMAPFLOAT_RMPTHRESHOLD {}
				AIPARAM C4DAIP_ALREMAPFLOAT_RMPCLAMPMIN {}
				AIPARAM C4DAIP_ALREMAPFLOAT_RMPCLAMPMAX {}
			}

		}

		AIPARAM C4DAIP_ALREMAPFLOAT_MASK {}
	}
}

