CONTAINER AINODE_ALCOMBINECOLOR
{
	NAME ainode_alCombineColor;

	INCLUDE GVbase;

	GROUP C4DAI_ALCOMBINECOLOR_MAIN_GRP
	{
		DEFAULT 1;

		AIPARAM C4DAIP_ALCOMBINECOLOR_INPUT1 {}
		AIPARAM C4DAIP_ALCOMBINECOLOR_INPUT2 {}
		AIPARAM C4DAIP_ALCOMBINECOLOR_INPUT3 {}
		AIPARAM C4DAIP_ALCOMBINECOLOR_COMBINEOP {}
	}
}

