CONTAINER AINODE_CRYPTOMATTE_AOV
{
	NAME ainode_cryptomatte_aov;

	INCLUDE GVbase;

	GROUP C4DAI_CRYPTOMATTE_AOV_MAIN_GRP
	{
		DEFAULT 1;

		AIPARAM C4DAIP_CRYPTOMATTE_AOV_PASSTHROUGH {}
		GROUP C4DAI_CRYPTOMATTE_AOV_AOVS_GRP
		{
			AIPARAM C4DAIP_CRYPTOMATTE_AOV_CRYPTO_ASSET_OVERRIDE {}
			AIPARAM C4DAIP_CRYPTOMATTE_AOV_CRYPTO_OBJECT_OVERRIDE {}
			AIPARAM C4DAIP_CRYPTOMATTE_AOV_CRYPTO_MATERIAL_OVERRIDE {}
			AIPARAM C4DAIP_CRYPTOMATTE_AOV_AOV_CRYPTO_ASSET {}
			AIPARAM C4DAIP_CRYPTOMATTE_AOV_AOV_CRYPTO_OBJECT {}
			AIPARAM C4DAIP_CRYPTOMATTE_AOV_AOV_CRYPTO_MATERIAL {}
		}

	}
}

