CONTAINER AINODE_ALINPUTVECTOR
{
	NAME ainode_alInputVector;

	INCLUDE GVbase;

	GROUP C4DAI_ALINPUTVECTOR_MAIN_GRP
	{
		DEFAULT 1;

		AIPARAM C4DAIP_ALINPUTVECTOR_INPUT {}
		AIPARAM C4DAIP_ALINPUTVECTOR_USERNAME {}
		AIPARAM C4DAIP_ALINPUTVECTOR_VECTOR {}
		AIPARAM C4DAIP_ALINPUTVECTOR_TYPE {}
		GROUP C4DAI_ALINPUTVECTOR_TRANSFORM_GRP
		{
			AIPARAM C4DAIP_ALINPUTVECTOR_MATRIX {}
			AIPARAM C4DAIP_ALINPUTVECTOR_COORDINATES {}
		}

	}
}

