CONTAINER AINODE_ALLAYER
{
	NAME ainode_alLayer;

	INCLUDE GVbase;

	GROUP C4DAI_ALLAYER_MAIN_GRP
	{
		DEFAULT 1;

		AIPARAM C4DAIP_ALLAYER_LAYER1 {}
		AIPARAM C4DAIP_ALLAYER_LAYER2 {}
		AIPARAM C4DAIP_ALLAYER_MIX {}
		AIPARAM C4DAIP_ALLAYER_DEBUG {}
		GROUP C4DAI_ALLAYER_AOVS_GRP
		{
			AIPARAM C4DAIP_ALLAYER_STANDARDCOMPATIBLEAOVS {}
			AIPARAM C4DAIP_ALLAYER_AOV_DIFFUSE_COLOR {}
			AIPARAM C4DAIP_ALLAYER_AOV_DIRECT_DIFFUSE {}
			AIPARAM C4DAIP_ALLAYER_AOV_DIRECT_DIFFUSE_RAW {}
			AIPARAM C4DAIP_ALLAYER_AOV_INDIRECT_DIFFUSE {}
			AIPARAM C4DAIP_ALLAYER_AOV_INDIRECT_DIFFUSE_RAW {}
			AIPARAM C4DAIP_ALLAYER_AOV_DIRECT_BACKLIGHT {}
			AIPARAM C4DAIP_ALLAYER_AOV_INDIRECT_BACKLIGHT {}
			AIPARAM C4DAIP_ALLAYER_AOV_DIRECT_SPECULAR {}
			AIPARAM C4DAIP_ALLAYER_AOV_INDIRECT_SPECULAR {}
			AIPARAM C4DAIP_ALLAYER_AOV_DIRECT_SPECULAR_2 {}
			AIPARAM C4DAIP_ALLAYER_AOV_INDIRECT_SPECULAR_2 {}
			AIPARAM C4DAIP_ALLAYER_AOV_SINGLE_SCATTER {}
			AIPARAM C4DAIP_ALLAYER_AOV_SSS {}
			AIPARAM C4DAIP_ALLAYER_AOV_REFRACTION {}
			AIPARAM C4DAIP_ALLAYER_AOV_EMISSION {}
			AIPARAM C4DAIP_ALLAYER_AOV_UV {}
			AIPARAM C4DAIP_ALLAYER_AOV_DEPTH {}
			AIPARAM C4DAIP_ALLAYER_AOV_LIGHT_GROUP_1 {}
			AIPARAM C4DAIP_ALLAYER_AOV_LIGHT_GROUP_2 {}
			AIPARAM C4DAIP_ALLAYER_AOV_LIGHT_GROUP_3 {}
			AIPARAM C4DAIP_ALLAYER_AOV_LIGHT_GROUP_4 {}
			AIPARAM C4DAIP_ALLAYER_AOV_LIGHT_GROUP_5 {}
			AIPARAM C4DAIP_ALLAYER_AOV_LIGHT_GROUP_6 {}
			AIPARAM C4DAIP_ALLAYER_AOV_LIGHT_GROUP_7 {}
			AIPARAM C4DAIP_ALLAYER_AOV_LIGHT_GROUP_8 {}
			AIPARAM C4DAIP_ALLAYER_AOV_ID_1 {}
			AIPARAM C4DAIP_ALLAYER_AOV_ID_2 {}
			AIPARAM C4DAIP_ALLAYER_AOV_ID_3 {}
			AIPARAM C4DAIP_ALLAYER_AOV_ID_4 {}
			AIPARAM C4DAIP_ALLAYER_AOV_ID_5 {}
			AIPARAM C4DAIP_ALLAYER_AOV_ID_6 {}
			AIPARAM C4DAIP_ALLAYER_AOV_ID_7 {}
			AIPARAM C4DAIP_ALLAYER_AOV_ID_8 {}
			AIPARAM C4DAIP_ALLAYER_AOV_CRYPTO_ASSET {}
			AIPARAM C4DAIP_ALLAYER_AOV_CRYPTO_OBJECT {}
			AIPARAM C4DAIP_ALLAYER_AOV_CRYPTO_MATERIAL {}
			AIPARAM C4DAIP_ALLAYER_AOV_SHADOW_GROUP_1 {}
			AIPARAM C4DAIP_ALLAYER_AOV_SHADOW_GROUP_2 {}
			AIPARAM C4DAIP_ALLAYER_AOV_SHADOW_GROUP_3 {}
			AIPARAM C4DAIP_ALLAYER_AOV_SHADOW_GROUP_4 {}
			AIPARAM C4DAIP_ALLAYER_AOV_SHADOW_GROUP_5 {}
			AIPARAM C4DAIP_ALLAYER_AOV_SHADOW_GROUP_6 {}
			AIPARAM C4DAIP_ALLAYER_AOV_SHADOW_GROUP_7 {}
			AIPARAM C4DAIP_ALLAYER_AOV_SHADOW_GROUP_8 {}
		}

	}
}

