CONTAINER AINODE_ALCEL
{
	NAME ainode_alCel;

	INCLUDE GVbase;

	GROUP C4DAI_ALCEL_MAIN_GRP
	{
		DEFAULT 1;

		GROUP C4DAI_ALCEL_SHADING_GRP
		{
			DEFAULT 1;

			AIPARAM C4DAIP_ALCEL_SURFACESHADER {}
			AIPARAM C4DAIP_ALCEL_DIFFUSEDIRECTSTRENGTH {}
			AIPARAM C4DAIP_ALCEL_DIFFUSERAMP {}
			AIPARAM C4DAIP_ALCEL_DIFFUSEINDIRECTSTRENGTH {}
			AIPARAM C4DAIP_ALCEL_DIFFUSEINDIRECTSATURATION {}
			AIPARAM C4DAIP_ALCEL_DIFFUSEINDIRECTTINT {}
		}

		GROUP C4DAI_ALCEL_AOVS_GRP
		{
			AIPARAM C4DAIP_ALCEL_AOV_DIRECT_DIFFUSE_CEL {}
			AIPARAM C4DAIP_ALCEL_AOV_DIRECT_DIFFUSE_RAW_CEL {}
			AIPARAM C4DAIP_ALCEL_AOV_INDIRECT_DIFFUSE_CEL {}
		}

	}
}

