CONTAINER AINODE_ALCOMBINEFLOAT
{
	NAME ainode_alCombineFloat;

	INCLUDE GVbase;

	GROUP C4DAI_ALCOMBINEFLOAT_MAIN_GRP
	{
		DEFAULT 1;

		AIPARAM C4DAIP_ALCOMBINEFLOAT_INPUT1 {}
		AIPARAM C4DAIP_ALCOMBINEFLOAT_INPUT2 {}
		AIPARAM C4DAIP_ALCOMBINEFLOAT_INPUT3 {}
		AIPARAM C4DAIP_ALCOMBINEFLOAT_COMBINEOP {}
	}
}

